### ISSUE TITLE
Not reading address correctly. Getting 0 value - Kaslr_shift is correct

### ISSUE THREAD

**Issue by itinerant-fox** [PsychoTea/maf_server#1]
iPhone-6:~/maf_server root# ./maf
wagwan
got tfp0: 0
got kaslr_shift: 19400000
IP: 1.0.0.0Started listening on 3
Got a client! 4
Read - Addr: fffffff0209be080, Value : 0000000000000000 0000000000000000
Read - Addr: fffffff0209be080, Value : 0000000000000000 0000000000000000
Read - Addr: fffffff02094af70, Value : 0000000000000000 0000000000000000
...............
..............

**Comment by itinerant-fox** [comment]
SSHing to an iPhone 6, 10.1.1 with Yalu jailbreak b7 . entitlements applied using ldid

**Comment by PsychoTea** [comment]
Issue with rk128/wk128 I'd expect. Not sure why it's returning all 0's though... seems unusual. I need to get round to testing this lol. 

Edit: seems it's failing to get hgsp4 (note the 'tfp: 0') because Yalu patches t_f_p() rather than using hgsp4. Will update.

**Comment by PsychoTea** [comment]
Should be fixed with latest commit.

**Comment by itinerant-fox** [comment]
Cool. It's working now. Thanks 👍
